### ISSUE TITLE
remove spritewell dependency

### ISSUE THREAD

**Issue by drewwells** [wellington/go-libsass#15]
go-libsass should not depend on spritewell. Because context is a concrete type, there's very little flexibility in how to pass data to custom handlers. We should instead pass interfaces to custom handlers.

This is a breaking change, that will require refactoring. It might be best to happen post 1.0 of Wellington.

**Comment by QuLogic** [comment]
spritewell still appears in `external/types/payload.go`; should this also be removed?

**Comment by QuLogic** [comment]
Oh, never mind, I see it was deleted in 0a1f17e219ef0e90b264c1f28a2e314f034f6f58, but just hasn't made it into a release yet.
