### ISSUE TITLE
[error] could not determine kind of name for C.sass_context_get_included_files_size

### ISSUE THREAD

**Issue by knksmith57** [wellington/go-libsass#4]
`go get github.com/wellington/go-libsass` fails with the following error:

```txt
golang ❱ go get -u github.com/wellington/go-libsass
# github.com/wellington/go-libsass
could not determine kind of name for C.sass_context_get_included_files_size
```

Any idea what's going on? 

```txt
golang ❱ go version
go version go1.4.2 darwin/amd64

golang ❱ brew install autoconf automake libtool mercurial pkg-config
Warning: autoconf-2.69 already installed
Warning: automake-1.15 already installed
Warning: pkg-config-0.28 already installed
Error: libtool-2.4.5 already installed
To install this version, first `brew unlink libtool'
Error: mercurial-3.3 already installed
To install this version, first `brew unlink mercurial'
```

**Comment by drewwells** [comment]
Do you have libsass installed, and what version? 

This project has a makefile for installing a local libsass: https://github.com/wellington/go-libsass#building-from-source-os-x-edition

**Comment by knksmith57** [comment]
I had 3.1.0, but simply upgrading to latest resolved this issue. Is there a minimum version required?

![screen shot 2015-06-14 at 2 55 23 pm](https://cloud.githubusercontent.com/assets/796851/8150195/8dec7256-12a5-11e5-8391-06bff3b0723d.png)

**Comment by drewwells** [comment]
Yeah were on 3.2.4. The API changes pretty frequently, so it's good to
update it regularly
