### ISSUE TITLE
Pass options to the libsass

### ISSUE THREAD

**Issue by Sendoushi** [wellington/go-libsass#42]
`New` function accepts options but I don't know how to pass options to the `libsass`.
Is it something supported already?

**Comment by drewwells** [comment]
https://godoc.org/github.com/wellington/go-libsass#New 

They accept anything that returns Option as well like Path https://godoc.org/github.com/wellington/go-libsass#Path

Here's how it is used in the wellington project https://github.com/wellington/wellington/blob/master/build.go#L254-L267

**Comment by Sendoushi** [comment]
Awesome, thanks for the example :)
I'll try to figure it out now.

**Comment by drewwells** [comment]
These optional arguments follow the functional options pattern. There's a good rundown of it works here: http://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis

**Comment by Sendoushi** [comment]
I just can't figure out the SourceMap. Here is my code:

```go
func (obj cssWriter) Write(p []byte) (n int, err error) {
	err = FileRemove(RemoveStruct{Src: obj.Dest})
	if err != nil {
		return
	}

	file, err := os.Create(obj.Dest)
	file.Write(p)
	return
}

comp, err := libsass.New(cssWriter{dest}, data,
		libsass.SourceMap(true, cssWriter{dest + ".map"}),
	)
```
Ideas on why?

**Comment by drewwells** [comment]
looks okay, I would check errors on file.Write()

any reason you don't pass a plain os.File? 

```
df, _ := os.Create(dest)
mf, _ := os.Create(dest+".map")
comp, err := libsass.New(df, data,
        libsass.SourceMap(true, mf),
    )
```

**Comment by Sendoushi** [comment]
Noobiness I guess. That is way better than what I have!
