### ISSUE TITLE
Concurrent task cancels out

### ISSUE THREAD

**Issue by Sendoushi** [wellington/go-libsass#44]
Hi,

I was trying to set concurrency with this package and a simple copy task.
It seems like `go-libsass` "cancels" other concurrencies.

Here are my [routines](https://github.com/Sendoushi/bedrock-utils/blob/go-system/modules/init.go#L72) and here is the code calling [go-libsass](https://github.com/Sendoushi/bedrock-utils/blob/go-system/modules/style.go#L156).

**Comment by drewwells** [comment]
You can not cancel goroutines. You can count them, manually, but there's no way to cause them to die. Are you seeing specific errors while compiling Sass?

**Comment by Sendoushi** [comment]
No. No errors. Things just don't happen. Sass compilation always happens.
I have implemented an "order of tasks" to run and if I leave sass compilationin its own order, everything works fine but that would remove the need for a go routine.

**Comment by drewwells** [comment]
Try using sync.Wait the program may exit before all routines are finished

**Comment by Sendoushi** [comment]
I'm already doing that...

**Comment by drewwells** [comment]
Need more details. Do the other routines start at all? Do they fail? What
are they expected to do?

**Comment by Sendoushi** [comment]
My project is a task system for other projects. You can copy, remove, rename files, minify css, minify js...
So, I set two copies of files and one sass (just as an example). The three tasks are go routines. If they run in the same `order` (which is a key I have to order the tasks as a pipeline) it becomes truly inconsistent with the style task. Sometimes a file copy and the other doesnt, sometimes it enters the go routine (noticing by the logs) but then there isn't a copy... If I comment the style task the copies work marvelously.

I know it is kind of a lot since it is another project to know about but did you understand this ramble?

**Comment by drewwells** [comment]
Definitely want to make sure go-libsass works with other code. I think I see what you are doing here.

Looking at the routine code, it looks like you are just logging errors rather than returning them up. What input are you providing and what are the logs saying? It looks like it should log even if the err is nil. 

One thing I do notice, since order isn't enforced in the file operations. It may run in a non-ideal order:

For example,
copy built.tar build/
remove build/*

when it may be intended to
remove build/*
copy built.tar build/

**Comment by Sendoushi** [comment]
Yes you can run removes and whatnot at the same time but that adds flexibility.
General rule, if you see this [example](https://github.com/Sendoushi/bedrock-utils/blob/go-system/test/example_build/build.toml) I set the remove first and then the rest.

The logs just say stuff like "Started task". What do you mean by input?

**Comment by drewwells** [comment]
Is this still relevant? It looks like the branch is gone and the project is now node. Feel free to comment if this is still an issue.
