### ISSUE TITLE
Can't build on macOS with Xcode 8.3

### ISSUE THREAD

**Issue by fordhurley** [wellington/go-libsass#46]
After upgrading Xcode to the latest version (8.3), I am unable to run the examples:

    $ cd examples/basic
    $ go run main.go
    signal: killed

**Comment by drewwells** [comment]
Xcode 8.3 broke cgo, more info: https://github.com/golang/go/issues/19734

**Comment by drewwells** [comment]
The current workaround is `go run -ldflags -s main.go`

**Comment by fordhurley** [comment]
I had the feeling that was the case, but was surprised that I hadn't heard about that yet! Hopefully having this issue here saves someone a headache.

**Comment by drewwells** [comment]
amen, thanks for finding this! Not sure on next steps right now, but all the released binaries probably will fail on OS X with xcode 8.3 now.

**Comment by drewwells** [comment]
go 1.8.1 is out fixing this issue https://golang.org/doc/devel/release.html#go1.8.minor
