### ISSUE TITLE
c compiling failes with `invalid flag in #cgo CPPFLAGS: -w`

### ISSUE THREAD

**Issue by hashworks** [wellington/go-libsass#54]
I get this with Go v1.9.4 and gcc v7.3.0.

Happens on `go install github.com/wellington/go-libsass` and on compilation when used in my project: `go build github.com/wellington/go-libsass/libs: invalid flag in #cgo CPPFLAGS: -w`

Linking against system libsass with the `dev` tag works fine.

**Comment by drewwells** [comment]
Oh, this might be a workaround: `export CGO_LDFLAGS_ALLOW=".*\.a"; ` can't work on this today but will test out soon.

**Comment by rikvdh** [comment]
@drewwells You can also remove the `-w` from `libs/wrap_main.go`, compiling the libs shall emit warnings. But shall compile fine.

**Comment by drewwells** [comment]
I see compile errors on 1.9 and 1.110 after removing -w
