### ISSUE TITLE
Error marshalling fails on 32-bit systems

### ISSUE THREAD

**Issue by QuLogic** [wellington/go-libsass#71]
I'm running a [test build](https://koji.fedoraproject.org/koji/taskinfo?taskID=32730003) across all arches using 0.9.2, and it fails 3 tests on 32-bit systems (i686 and armv7hl):
```
--- FAIL: TestUnmarshalError (0.00s)
    encoding_test.go:78: got:  wanted: error message
--- FAIL: TestMarshalError (0.00s)
    encoding_test.go:265: got:
        
        wanted:
        error has been thrown
--- FAIL: TestError_simple (0.00s)
    export_test.go:28: got:  wanted: help me
```
These are all tests that attempt to marshal and unmarshal an error. It does not appear to matter whether I build with the bundled libsass or a system one.

**Comment by drewwells** [comment]
Nice finds. Those tests are basically wrappers around the libsass library. Can you reproduce those problems in that project?

**Comment by QuLogic** [comment]
I think I figured out the problem. The location of the value for `Sass_String` is one struct member later than for `Sass_Error`. On 64-bit systems, the two first members are packed together, but they aren't on 32-bit systems. So calling the string accessor on an error value returns garbage.
